---
title: "Final Model"
author: "STOR 320.01 Group 21"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("devtools", repos = "http://cran.us.r-project.org")
library(tidyverse)
library(dplyr)
library(plyr)
library(tidyr)
library(ggplot2)
library(maps)
library(mapproj)
devtools::install_github("wmurphyrd/fiftystater")
library(fiftystater)
library(randomForest) 
library(ranger)
library(readr)
library(tibble)
library(scales)
```

--------------------------------------------------------------------------------------------------------------------------------

#Creator: Evan Vitkus


###Q1: How does level of education affect pay for H1B immigrant workers?

```{r}
dataOrg <- read_csv("D:/Document/2018-2019/Stor320/Final Project/PWD_Disclosure_Data_FY2018_EOY.csv")
```
 Make dataset
```{r}
dataCleanModel <- dataOrg %>% select(`EMPLOYER _CITY`,`EMPLOYER _STATE`,`EMPLOYER _COUNTRY`,JOB_TITLE,WORK_HOUR_NUM_BASIC,WORK_HOUR_NUM_OVERTIME, TRAVEL_REQUIRED,PRIMARY_EDUCATION_LEVEL,MAJOR,SECOND_DIPLOMA,SECOND_DIPLOMA_MAJOR,TRAINING_REQUIRED,NUMBER_OF_MONTHS_TRAINING,EMP_EXPERIENCE_REQUIRED,EMP_EXPERIENCE_MONTHS,PWD_WAGE_RATE)

dataCleanModel <- dataCleanModel %>% select(-SECOND_DIPLOMA_MAJOR, -WORK_HOUR_NUM_BASIC, -WORK_HOUR_NUM_OVERTIME)
dataCleanModel <- dataCleanModel %>% select(-MAJOR)

dataCleanModel=dataCleanModel %>% mutate_if(is.character, as.factor)
head(dataCleanModel )

```
Clean dataset
```{r}
dataCleanModel = dataCleanModel %>% drop_na(PWD_WAGE_RATE)
dataCleanModel$NUMBER_OF_MONTHS_TRAINING[is.na(dataCleanModel$NUMBER_OF_MONTHS_TRAINING)] <- 0
dataCleanModel$EMP_EXPERIENCE_MONTHS[is.na(dataCleanModel$EMP_EXPERIENCE_MONTHS)] <- 0
dataCleanModel$EMP_EXPERIENCE_MONTHS[is.na(dataCleanModel$EMP_EXPERIENCE_MONTHS)] <- 0
dataCleanModel = dataCleanModel %>% drop_na()
dataCleanModel = dataCleanModel %>% dplyr::rename(EMPLOYER_CITY = `EMPLOYER _CITY`, EMPLOYER_STATE = `EMPLOYER _STATE`, EMPLOYER_COUNTRY = `EMPLOYER _COUNTRY`)
dataCleanModel <- tibble::rowid_to_column(dataCleanModel, "ID")
head(dataCleanModel)
```


Make training and testing dataset
```{r}
smp_size <- floor(0.75 * nrow(dataCleanModel))

## set the seed to make your partition reproducible
set.seed(123)
train_ind <- sample(seq_len(nrow(dataCleanModel)), size = smp_size)

train <- dataCleanModel[train_ind, ]
test <- dataCleanModel[-train_ind, ]

head(train)
```
```{r}
#randModel = randomForest(formula = PWD_WAGE_RATE ~ ., data = train, num.trees = 5, na.action = na.exclude)

#p<-predict(rf,test)
```

```{r}

```

run model and find predictions
```{r}
rf = ranger(formula = PWD_WAGE_RATE ~ .-ID, data = train, num.trees = 500, importance = "impurity", respect.unordered.factors = "ignore",write.forest = TRUE)

p<-predict(rf,test)

head(p$predictions)
```

print model details and importance factors
```{r}

#p$prediction.error
#importance(p)

#print(rf)
#getTerminalNodeIDs(rf,train)
#varImp(p)

#importance(rf)

#head(importance)

#p$variable.importance
#names(p)
#df.p <- data.frame(idx=test$idx,
#                   predictions=p$pred) %>% arrange(idx)

#predictVal = p$predictions
#finalModel$predval = predictVal
#finalModel$actualVal = dataCleanModel$PWD_WAGE_RATE
#head(finalModel)
#finalPred
#finalPred <- dataCleanModel %>% mutate(fitted = p$predictions)

print(rf)
names(importance(rf))
imp = importance(rf)
imp = as_tibble(imp)
imp$label = names(importance(rf))
head(imp)
ggplot(imp) + geom_col(mapping = aes(x=label, y=value))+
  ylab("Importance") + 
  xlab("Parameter")+
  theme_light()+ggtitle("Importance of Parameters") + 
  theme_classic()+
  theme(
    plot.title = element_text(color="blue", size=14, face="bold.italic"),
    axis.title.x = element_text(color="blue", size=14, face="bold"),
    axis.title.y = element_text(color="blue", size=14, face="bold",margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0)),
    axis.text.x = element_text(angle=0),
    axis.ticks.x = element_blank(),
    )+
  coord_flip()
```

Graph predictions and actual
```{r}
paco=p$predictions
tibPac <- as_tibble(paco)

ggplot(tibPac) + geom_boxplot(mapping = aes(y=value))   + 
  ylab("Wage Rate (Dollars)") + 
  theme_light()+ggtitle("Predicted Wage Rates") + 
  theme_classic()+
  theme(
    plot.title = element_text(color="blue", size=14, face="bold.italic"),
    axis.title.x = element_text(color="blue", size=14, face="bold"),
    axis.title.y = element_text(color="blue", size=14, face="bold",margin = ggplot2::margin(t = 0, r = 20, b = 0, l = 0)),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    )+
  scale_y_continuous(breaks=seq(0,300000,100000),labels =  dollar_format())

dataCleanModel %>% filter(PWD_WAGE_RATE<500000) %>% ggplot() + geom_boxplot(mapping = aes(y=PWD_WAGE_RATE))   + 
  ylab("Wage Rate (Dollars)") + 
  theme_light()+ggtitle("Actual Wage Rates") + 
  theme_classic()+
  theme(
    plot.title = element_text(color="blue", size=14, face="bold.italic"),
    axis.title.x = element_text(color="blue", size=14, face="bold"),
    axis.title.y = element_text(color="blue", size=14, face="bold",margin = ggplot2::margin(t = 0, r = 20, b = 0, l = 0)),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    )+
  scale_y_continuous(breaks=seq(0,300000,100000),labels =  dollar_format())
```

Repeat above steps for a subset of the data
```{r}
dataCleanModel2 <- dataCleanModel %>% filter(PWD_WAGE_RATE <= 500000)

smp_size2 <- floor(0.75 * nrow(dataCleanModel2))

## set the seed to make your partition reproducible
set.seed(123)
train_ind2 <- sample(seq_len(nrow(dataCleanModel2)), size = smp_size2)

train2 <- dataCleanModel[train_ind2, ]
test2 <- dataCleanModel[-train_ind2, ]

head(train2)

```

```{r}
rf2 = ranger(formula = PWD_WAGE_RATE ~ .-ID, data = train2, num.trees = 500, importance = "impurity", respect.unordered.factors = "ignore",write.forest = TRUE)

p2<-predict(rf2,test2)

head(p2$predictions)
```

```{r}
print(rf2)
names(importance(rf2))
imp2 = importance(rf2)
imp2 = as_tibble(imp2)
imp2$label = names(importance(rf2))
#head(imp2)
ggplot(imp2) + geom_col(mapping = aes(x=label, y=value))+
  ylab("Importance") + 
  xlab("Parameter")+
  theme_light()+ggtitle("Importance of Parameters") + 
  theme_classic()+
  theme(
    plot.title = element_text(color="blue", size=14, face="bold.italic"),
    axis.title.x = element_text(color="blue", size=14, face="bold"),
    axis.title.y = element_text(color="blue", size=14, face="bold",margin = ggplot2::margin(t = 0, r = 20, b = 0, l = 0)),
    axis.text.x = element_text(angle=0),
    axis.ticks.x = element_blank(),
    )+
  coord_flip()
```

```{r}
paco2=p$predictions
tibPac2 <- as_tibble(paco2)
ggplot(tibPac2) + geom_boxplot(mapping = aes(y=value))   + 
  ylab("Wage Rate (Dollars)") + 
  theme_light()+ggtitle("Predicted Wage Rates") + 
  theme_classic()+
  theme(
    plot.title = element_text(color="blue", size=14, face="bold.italic"),
    axis.title.x = element_text(color="blue", size=14, face="bold"),
    axis.title.y = element_text(color="blue", size=14, face="bold",margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0)),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    )+
  scale_y_continuous(breaks=seq(0,300000,100000),labels =  dollar_format())

dataCleanModel2 %>% filter(PWD_WAGE_RATE<500000) %>% ggplot() + geom_boxplot(mapping = aes(y=PWD_WAGE_RATE))   + 
  ylab("Wage Rate (Dollars)") + 
  theme_light()+ggtitle("Actual Wage Rates") + 
  theme_classic()+
  theme(
    plot.title = element_text(color="blue", size=14, face="bold.italic"),
    axis.title.x = element_text(color="blue", size=14, face="bold"),
    axis.title.y = element_text(color="blue", size=14, face="bold",margin = ggplot2::margin(t = 0, r = 20, b = 0, l = 0)),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    )+
  scale_y_continuous(breaks=seq(0,300000,100000),labels =  dollar_format())
```

